apiVersion: v1
kind: Service
metadata:
  name: "supersonic-service"
  labels:
    app: "supersonic-fe"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: "supersonic-fe"
  sessionAffinity: None
  type: NodePort
